# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='Photo',
        ),
    ]
